# Generated by Django 5.2.11 on 2026-04-16 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid dotted slug (lowercase letters, numbers, hyphens, separated by dots).', regex='^[a-z0-9]+(?:[.-][a-z0-9]+)*$')]),
        ),
    ]
