# Generated by Django 5.2.11 on 2026-05-04 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_alter_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='patrons',
            field=models.ManyToManyField(blank=True, help_text='Users who are patrons of this category.', related_name='patron_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
